#!/bin/bash
#
# idea wrapper
#

set -e

# Set android sdk home
[ -d "${HOME}/.opt/android-sdks" ] \
  && export ANDROID_SDK="${HOME}/.opt/android-sdks" \
  && export ANDROID_HOME="${ANDROID_SDK}"

# Set android ndk home
[ -d "${HOME}/.opt/android-ndk" ] \
  && export ANDROID_NDK="${HOME}/.opt/android-ndk"

if [[ -d ${HOME}/.config-xmonad/android-studio/bin-conf ]] && [[ -d ${HOME}/.opt/android-studio/bin ]]; then
  cp ${HOME}/.config-xmonad/android-studio/bin-conf/* ${HOME}/.opt/android-studio/bin/
fi

exec ~/.opt/android-studio/bin/studio.sh
