#!/bin/bash
#
# Dmenu launch wrapper
#
# Author: Thomas Frössman  ( thomasf@jossystem.se / http://thomas.jossystem.se )
# Updates to this file will probably be available at https://github.com/thomasf/dotfiles/
#

set -e

tr=urxvt

if [ `which yeganesh` ]; then
    cmd=`yeganesh -x`
else
    cmd=`dmenu_path | dmenu -i`
fi

case $cmd in
    alsamixer|htop|irssi|weechat-curses|ncmpcpp)
        exec $tr -name $cmd -e $cmd
        ;;
    wireshark|synaptic|zenmap|firestarter|reboot)
        exec gksudo $cmd
        ;;
    shutdown)
        exec gksudo "shutdown now -h"
        ;;
    *)
        exec $cmd
        ;;
esac
