#!/bin/bash
#
# Dmenu launch wrapper
#
# Author: Thomas Frössman  ( thomasf@jossystem.se / http://thomas.jossystem.se )
# Updates to this file will probably be available at https://github.com/thomasf/dotfiles/
#

set -e

tr=urxvt

if [ `which yeganesh` ]; then
    cmd=`yeganesh -p appmenu -x -- -l 25`
else
    cmd=`dmenu_path | dmenu -i -l 25`
fi

case $cmd in
    saidar)
	    exec $tr -name saidar -e saidar -c
	    ;;
    alsamixer|htop|irssi|weechat-curses|ncmpcpp|pamixer)
        exec $tr -name $cmd -e $cmd
        ;;
    wireshark|synaptic|zenmap|firestarter|reboot|nm-connection-editor)
        exec gksudo $cmd
        ;;
    shutdown)
        exec gksudo "shutdown now -h"
        ;;
    *)
        exec $cmd
        ;;
esac
