#!/bin/bash
#
# Dmenu launch wrapper
#
# Author: Thomas Frössman  ( thomasf@jossystem.se / http://thomas.jossystem.se )
# Updates to this file will probably be available at https://github.com/thomasf/dotfiles/
#

set -e

ppath() {
 [ -d "${1}" ] && PATH="${1}:${PATH}" || true
}

# ppath ~/.opt/idea/bin

tr=urxvt

if [ `which yeganesh` ]; then
  input=`yeganesh -p appmenu -x -- -p launch -l 25`
else
  input=`dmenu_path | dmenu -p launch -i -l 25`
fi

set -- nil $input
shift

cmd=$1
shift || true


case $cmd in
  saidar)
    exec urxvt -e saidar -c
	;;
  alsamixer|htop|irssi|weechat-curses|ncmpcpp|pamixer|dstat|ping)
    exec urxvt -e $cmd $*
    ;;
  iptraf-ng|aptitude|iotop)
    exec urxvt -e sudo $cmd $*
    ;;
  wireshark|synaptic|zenmap|firestarter|nm-connection-editor|gnome-disks|baobab|usb-creator-gtk)
    exec gksudo $cmd $*
    ;;
  dropbox)
    exec dropboxmenu
    ;;
  google-chrome|w)
    exec www $*
    ;;
  man)
    init=""
    [ -e ~/.emacs.d/init-low.el ] && init="-l ~/.emacs.d/init-low";
    exec emacs -q $init -eval "(man \"$*\")"
    ;;
  reboot|shutdown|suspend|hibernate)
    exec a.$cmd
    ;;
  *)
    exec $cmd $*
    ;;
esac
