#!/bin/sh
#
# Switch between light and dark mode.
#

set -e

golight() {
    bgset l
    rm -f ~/.config/darkmode
    panels
}

godark() {
    bgset d
    [ ! $(id -u) -eq 0 ] && touch ~/.config/darkmode
    panels
}


cmd=${1}
case $cmd in
    l|light)
        golight
        ;;
    d|dark)
        godark
        ;;
    t|toggle|*)
        if [ -e ~/.config/darkmode ]; then
            golight
        else
            godark
        fi
        ;;
esac
