#!/bin/sh
#
# Switch between light and dark mode.
#

# set -e


golight() {
    rm -f ~/.config/darkmode
    xsetroot -solid '#eee8d5'
    panels
    xrdb ~/.config-xmonad/xresources/light
    xmonad --restart
}

godark() {
    [ ! $(id -u) -eq 0 ] && touch ~/.config/darkmode
    xsetroot -solid '#073642'
    panels
    xrdb ~/.config-xmonad/xresources/dark
    xmonad --restart
}

cmd=${1}
case $cmd in
    l|light)
        golight
        ;;
    d|dark)
        godark
        ;;
    t|toggle|*)
        if [ -e ~/.config/darkmode ]; then
            golight
        else
            godark
        fi
        ;;
esac

# Local Variables:
# eval: (rainbow-mode)
# End:
