#!/bin/sh
#
# Dmenu wrapper, changed colors
#
# Author: Thomas Frössman  ( thomasf@jossystem.se / http://thomas.jossystem.se )
# Updates to this file will probably be available at https://github.com/thomasf/dotfiles/
#


#exec /usr/bin/dmenu -nb '#303030' -nf '#FFFFFF' -sb '#3465A4' -sf '#FFFFFF' -i $*
exec /usr/bin/dmenu -nb '#b58900' -nf '#fdf6e3' -sb '#fdf6e3' -sf '#586e75' -i $*
