#!/bin/sh
#
# Dmenu wrapper, changed colors
#
# Author: Thomas Frössman  ( thomasf@jossystem.se / http://thomas.jossystem.se )
# Updates to this file will probably be available at https://github.com/thomasf/dotfiles/
#

exec /usr/bin/dmenu -nb '#002b36' -nf '#268bd2' -sb '#268bd2' -sf '#002b36' -i $*
