#!/bin/sh
#
# Get properies for xwindows.
# Useful when configuring xmonad window rules
#

xprop | sed -n '
    /^WM_CLASS/s/.* = "\(.*\)", "\(.*\)"/instance: \1\nclass: \2/p;
    /^WM_NAME/s/.* = "\(.*\)"/title: \1/p'
