#!/bin/bash
#
# idea wrapper
#

set -e

if [[ -d ${HOME}/.config-private/idea13u/bin-conf ]] && [[ -d ${HOME}/.opt/idea/bin ]]; then
  cp ${HOME}/.config-private/idea13u/bin-conf/* ${HOME}/.opt/idea/bin/
fi

exec ~/.opt/idea/bin/idea.sh
