#!/bin/bash
#
# Dmenu network manager connection selection menu
#
# Author: Thomas Frössman  ( thomasf@jossystem.se / http://thomas.jossystem.se )
# Updates to this file will probably be available at https://github.com/thomasf/dotfiles/
#

set -e

nmcli -t -f name,devices con status | dzen2 -p 2 -bg '#859900' -fg '#002b36' -ta c -x 50 -y 250 -w 300 -h 50 &
uuid=`nmcli -e yes -m tabular -t -f uuid,name con list | dmenu -i -l 15 | cut -d: -f1`
[ $uuid ] && gksudo nmcli con up uuid $uuid
