#!/bin/sh

if [ -e ~/.config/darkmode ]; then
    mode=dark
    bg=0x002b36
else
    mode=light
    bg=0xfdf6e3
fi

pids="$(pidof xmobar)"
xmobar ~/.config-xmonad/xmobar/${mode}-top-x0 -x 0 &
xmobar ~/.config-xmonad/xmobar/${mode}-top -x 1 &
xmobar ~/.config-xmonad/xmobar/${mode}-bottom -x 0 &
xmobar ~/.config-xmonad/xmobar/${mode}-bottom -x 1 &

[ ! -z "${pids}" ] && sleep 1 && kill $pids
pkill trayer
trayer --edge top --align right --widthtype percent --width 10 --height 18 --tint ${bg} --alpha 0 --transparent true &
