#!/bin/bash
#
# Set terminal font (urxvt only, maybe)
#
# Author: Thomas Frössman  ( thomasf@jossystem.se / http://thomas.jossystem.se )
# Updates to this file will probably be available at https://github.com/thomasf/dotfiles/
#

fSize=${1:-10}
fSel=${2:-a}

unset font

case "${fSel}" in
    a)
	font="xft:Anonymous Pro-$fSize"
	;;
    c)
	font="xft:Consolas-$fSize"
	;;
    t)
	font="-*-terminus-*-r-normal-*-$fSize-*-*-*-*-*-*-1"
	;;
esac

[[ -n ${font} ]] && echo -en "\033]50;$font\007"
