#!/bin/bash

set -e

mkdir -p ~/Pictures/scrot/
cd ~/Pictures/scrot/



shot() {
  local suffix=${1}
  shift
  local fn="$(date '+%Y-%m-%d  %H %M %S')  ${suffix}.png"
  rm -f "${fn}"
  maim -u ${@} "${fn}"
  local msg="saved ${fn}"
  notify-send -u normal -a shorter "sshot" "<span font='12'>${msg}</span>"
  cat "${fn}" | xclip -selection c -t image/png
}

case ${1} in
  focused)
    shot "window" -n 2 -i $(xdotool getactivewindow)
    ;;
  full)
    shot "full" -B
    ;;
  "select"|*)
    sshot-select
    notify-send -u normal -a shorter "sshot" "<span font='12'>selection saved</span>"
    ;;
esac
