#!/bin/bash
#
# Launch terminals
#
# Author: Thomas Frössman  ( thomasf@jossystem.se / http://thomas.jossystem.se )
#
#

set -e

cmd=${1}
case $cmd in
    l|light)
        shift 1
        exec urxvt -name LURxvt $*
        ;;
    large)
        shift 1
        xsexec urxvt -name large_term $*
        ;;
    *)
        exec urxvt $*
        ;;
esac
