#!/bin/bash
#
# Launch terminals
#
# Author: Thomas Frössman  ( thomasf@jossystem.se / http://thomas.jossystem.se )
#
#

set -e

if hash alacritty 2>/dev/null; then
  dir="${XDG_CONFIG_HOME:-${HOME}/.config-xmonad}/alacritty"
  config="alacritty.${HOSTNAME:-tmp}.yml"
  if cp -n "${dir}/_default.yml" "${dir}/${config}" 2>/dev/null; then
    exec alacritty --config-file "${dir}/${config}" "$@"
  else
    exec alacritty "$@"
  fi
else
  exec urxvt "$@"
fi
