#!/bin/bash
#
# Opens an regular web browser
#
# Author: Thomas Frössman  ( thomasf@jossystem.se / http://thomas.jossystem.se )
# Updates to this file will probably be available at https://github.com/thomasf/dotfiles/
#

declare -a args

case ${HOSTNAME} in
  transwhale)
    args+="--enable-native-gpu-memory-buffers "
    args+="--enable-gpu-rasterization "
    args+="--audio-buffer-size=1024 "
    ;;
esac


case $(basename ${0}) in
  www-temp)
    args+="--incognito "
    ;;
  www-window)
    args+="--new-window "
    ;;
esac

exec google-chrome $args "$@"
