#!/bin/sh
#
# Opens an url as an www app (single window web browser)
#
# Author: Thomas Frössman  ( thomasf@jossystem.se / http://thomas.jossystem.se )
# Updates to this file will probably be available at https://github.com/thomasf/dotfiles/
#

set -e

google-chrome -app="${1}"
