#!/bin/sh
#
# Start a new google chrome session for development
#
# Author: Thomas Frössman  ( thomasf@jossystem.se / http://thomas.jossystem.se )
# Updates to this file will probably be available at https://github.com/thomasf/dotfiles/
#
# Command line switches reference: http://src.chromium.org/svn/trunk/src/chrome/common/chrome_switches.cc

set -e

profiles_dir=~/.config/chrome-dev

mkdir -p $profiles_dir

cd $profiles_dir

profile=`find . -mindepth 1 -maxdepth 1 -type d | cut -d / -f 2 | dmenu -p profile`
[ -z $profile ] && profile=_default

#    --remote-debugging-port=9222 \

google-chrome \
    --allow-file-access \
    --enable-memory-info \
    --enable-extension-timeline-api \
    --disable-background-mode  \
    --disable-restore-session-state \
    --disable-sync \
    --disable-translate \
    --enable-benchmarking \
    --purge-memory-button \
    --ignore-certificate-errors \
    --disable-web-security \
    --user-data-dir=$profiles_dir/$profile \
    --no-default-browser-check \
    --no-first-run \
    $*
