#!/bin/sh
#
# Start a new google chrome session for development
#
# Author: Thomas Frössman  ( thomasf@jossystem.se / http://thomas.jossystem.se )
# Updates to this file will probably be available at https://github.com/thomasf/dotfiles/
#
# Command line switches reference: http://src.chromium.org/svn/trunk/src/chrome/common/chrome_switches.cc

set -e

exec chromium-browser \
    --incognito \
    --enable-memory-info \
    --enable-extension-timeline-api \
    --disable-background-mode  \
    --enable-benchmarking \
    --enable-panels \
    --purge-memory-button \
    --reload-killed-tabs \
    --use-more-webui \
    --use-pure-views \
    --ignore-certificate-errors \
    --disable-web-security \
    $*
