#!/bin/sh
#
# This script does the following
# * ensures a sane build environment for xmonad on ubuntu
# * fetches/updates xmonad and xmonad contrib from  darcs repositories
# * applies custom patches
# * compiles and installs xmonad and xmonad contrib
# * recompiles xmonad
#
# Author: Thomas Frössman  ( thomasf@jossystem.se / http://thomas.jossystem.se )
# Updates to this file will probably be available at https://github.com/thomasf/dotfiles/
#
set -e

[ ! $(which git) ] && echo no git installed && exit
[ ! $(which cabal) ] && echo no cabal installed && exit

mkdir -p ~/.opt
cd ~/.opt

set +e
(
  if [ ! -d xmonad ]; then
    git clone git@github.com:thomasf/xmonad.git
  fi
)
(
  if [ ! -d xmonad-contrib ]; then
    git clone git@github.com:thomasf/xmonad-contrib.git
  fi
)
(
  cd xmonad
  git pull
  cabal install
)
(
  cd xmonad-contrib
  git pull
  cabal install
)

~/.cabal/bin/xmonad --recompile
