#!bash
#
# This file might be sourced during installation with hsadmin
#

if [ -e "${HOME}/.config/dunst/dunstrc" ]; then
    mkdir -p "${HOME}/.config/dunst/" \
        && ln -fs "$(pwd)/.config-xmonad/dunstrc" "${HOME}/.config/dunst/"
fi
[ -e "${HOME}/.config/gtk-3.0" ] \
    || ln -fs "$(pwd)/.config-xmonad/gtk/gtk-3.0" "${HOME}/.config/"

[ -e "${HOME}/.themes" ] \
    || ln -fs "$(pwd)/.config-xmonad/gtk/themes" "${HOME}/.themes"

if [ ! -e "${HOME}/.config/fontconfig/conf.d" ]; then
    mkdir -p "${HOME}/.config/fontconfig/" \
        && ln -fs "$(pwd)/.config-xmonad/fontconfig.d" "${HOME}/.config/fontconfig/conf.d"
fi

# [ -e "${HOME}/.fonts.conf.d" ] \
#     || ln -fs "$(pwd)/.config-xmonad/fontconfig.d" "${HOME}/.fonts.conf.d"

set +x
