#!/bin/bash

if ! [ -d xmonad ]; then
  git clone git@github.com:thomasf/xmonad.git
fi

if ! [ -d xmonad-contrib ]; then
  git clone git@github.com:thomasf/xmonad-contrib.git
fi

cabal v1-install happy
cabal v1-install pango

(
cd xmonad
cabal v1-install --force-reinstalls .
)

(
  cd xmonad-contrib
  cabal v1-install --force-reinstalls .
)
