[colors]

  [colors.primary]
    background = "#fdf6e3"
    foreground = "#657b83"

  [colors.cursor]
    text = "#fdf6e3"
    cursor = "#657b83"

  [colors.normal]
    black = "#073642"
    red = "#dc322f"
    green = "#859900"
    yellow = "#b58900"
    blue = "#268bd2"
    magenta = "#d33682"
    cyan = "#2aa198"
    white = "#eee8d5"

  [colors.bright]
    black = "#002b36"
    red = "#cb4b16"
    green = "#586e75"
    yellow = "#657b83"
    blue = "#839496"
    magenta = "#6c71c4"
    cyan = "#93a1a1"
    white = "#fdf6e3"

  [colors.search]

    [colors.search.matches]
      foreground = "#ffffff"
      background = "#d33682"

  [colors.footer_bar]
    foreground = "#ffffff"
    background = "#268bd2"
