window:
  decorations: buttonless
  padding:
    x: 8
    'y': 8

font:
  normal:
    family: "PragmataPro Mono"
    style: Regular

  bold:
    family: "PragmataPro Mono"
    style: Bold

  italic:
    family: "PragmataPro Mono"
    style: Italic

key_bindings:
  - { key: Key0,   mods: Command,            action: ResetFontSize    }
  - { key: Equals, mods: Command,            action: IncreaseFontSize }
  - { key: Plus,   mods: Command,            action: IncreaseFontSize }
  - { key: Minus,  mods: Command,            action: DecreaseFontSize }
  - { key: K,      mods: Command,            action: ClearHistory     }
  - { key: V,      mods: Command,            action: Paste            }
  - { key: C,      mods: Command,            action: Copy             }
  - { key: H,      mods: Command,            action: Hide             }
  - { key: M,      mods: Command,            action: Minimize         }
  - { key: Q,      mods: Command,            action: Quit             }
  - { key: W,      mods: Command,            action: Quit             }
  - { key: 'N',    mods: Command,            action: SpawnNewInstance }
  - { key: F,      mods: Command|Control,    action: ToggleFullscreen }
