#!/bin/bash
killall -q compton
set -e

if [ -x $HOME/.opt/compton/compton ]; then
  compton="${HOME}/.opt/compton/compton"
  if [[ $HOSTNAME == transwhale ]]; then
    $compton --config ~/.config-xmonad/compton-xrender.conf &
  else
    $compton --config ~/.config-xmonad/compton-glx.conf &
  fi
fi
