#!/bin/bash
#
# idea wrapper
#

set -e

case ${1} in
  format|inspect)
    exec ~/.opt/idea/bin/idea.sh dontReopenProjects "$@"
    ;;
  *)
    exec nohup ~/.opt/idea/bin/idea.sh nosplash dontReopenProjects "$@" > /dev/null 2>&1 &
    ;;
esac
