#!/bin/bash

setl() {
  local layout
  local id
  local all=$3
  local verbose=1
  local cmd
  layout=$2
  ids=$(xinput -list | grep -i "${1}" | grep -o id=[0-9]. | grep -o [0-9].)
  if [ "${ids}" ]; then
    for id in $ids; do
      cmd="xkbcomp"
      cmd="${cmd} -I$HOME/.config-xmonad/xkb"
      [ -z ${all} ] && cmd="${cmd} -i $id"
      cmd="${cmd} $HOME/.config-xmonad/xkb/$layout $DISPLAY"
      if [ -z ${verbose} ]; then
        ${cmd} 2>/dev/null
      else
        ${cmd}
      fi
    done
  fi
}


setl "Apple Internal Keyboard" my-mac-us-ctrl-caps-super 1
setl "DATACOMP SteelS" my-se-caps-ctrl-super 1
setl "TrulyErgonomic.com" my-us-intl 1
setl "8BitDo 8BitDo Retro Keyboard" my-us-intl 1
setl "USBPS2" my-us-intl 1
setl "Kenth" my-mac-us-ctrl-caps-super 1
setl "Apple Internal Keyboard" my-mac-us-ctrl-caps-super
setl "AT Translated Set 2 keyboard" my-us-intl


# TODO: for some reasons the xkb caps lock keyswap does not work on the lenovo laptop
if [ "$HOST" == "yak" ]; then
  xmodmap -e "remove Lock = Caps_Lock"
  xmodmap -e "keysym Caps_Lock = Control_L"
  xmodmap -e "add Control = Control_L"
fi
