#!/bin/bash
#
# Nautilus wrapper
#

bin=/usr/bin/nautilus
nargs="--new-window"

#bin=/usr/bin/pcmanfm
#nargs="-n"

if [ $# -eq 0 ]; then

    source ~/.config-base/bash/common
    source "${__BASH}/z"

    if [ $(which wsname) ]; then
        name="$(wsname -p)"
        case $name in
            home|temp|chat|nodes|dash|NSP)
                cd ${HOME}
                ;;
            emacs)
                cd ~/.emacs.d
                ;;
            www|share|mail)
                cd ~/Downloads
                ;;
            books)
                cd ~/books
                ;;
            *)
                _z "${HOME}" "${name/-/ }"
                ;;
        esac
    fi
    exec $bin $nargs .
else
    exec $bin $nargs "$@"

fi
