#!/bin/bash

case $(gsettings get org.gnome.nautilus.preferences recursive-search) in
  "'never'")
    next="local-only"
    ;;
  "'local-only'")
    next="never"
    ;;

  # "'never'")
  #   next="local-only"
  #   ;;
  # "'local-only'")
  #   next="always"
  #   ;;
  # "'always'")
  #   next="never"
  #   ;;
  *)
    next="never"
    ;;
esac


notify-send -a short -r 616797154 "recursive search: ${next}" &
exec gsettings set org.gnome.nautilus.preferences recursive-search "'${next}'"
