#!/bin/bash
#
# Opens an regular web browser
#
# Author: Thomas Frössman  ( thomasf@jossystem.se / http://thomas.jossystem.se )
# Updates to this file will probably be available at https://github.com/thomasf/dotfiles/
#

declare -a args

args+="--hide-crash-restore-bubble "

case ${HOSTNAME} in
  transwhale|flam)
    args+="--enable-native-gpu-memory-buffers "
    args+="--enable-gpu-rasterization "
    # args+="--audio-buffer-size=1024 "
    if [ -e ~/.config/darkmode ]; then
      args+="--enable-features=WebUIDarkMode "
      args+="--force-dark-mode "
    else
      args+="--disable-features=WebUIDarkMode "
      # args+="--force-light-mode "
    fi
    ;;
esac


case $(basename ${0}) in
  www-temp)
    args+="--incognito "
    ;;
  www-window)
    args+="--new-window "
    ;;
esac


if hash google-chrome 2>/dev/null; then
  exec google-chrome $args "$@"
elif [ -e /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome ]; then
  exec /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome $args "$@"
else
  exit 1
fi
