#!/bin/bash

set -e

for file in dark-*; do

    lightname=light${file##dark}
    cp $file $lightname
    sed -i 's/002b36/fdf6e3/g' $lightname
    sed -i 's/073642/eee8d5/g' $lightname
    sed -i 's/586e75/93a1a1/g' $lightname
    sed -i 's/657b83/839496/g' $lightname
done
